USE MedicalManagement
Go

INSERT INTO Speciality VALUES
 ('Allergy',NEWID())
,('Anesthesia',NEWID())
,('Bariatric Medicine/Surgery',NEWID())
,('Burn/Trauma',NEWID())
,('Cardiac Catheterization',NEWID())
,('Cardiology',NEWID())
,('Cardiovascular Surgery',NEWID())
,('Colorectal Surgery',NEWID())
,('Dermatology',NEWID())
,('Electrophysiology',NEWID())
,('Emergency Medicine',NEWID())
,('Endocrinology',NEWID())
,('Family Practice',NEWID())
,('Gastroenterology',NEWID())
,('General Surgery',NEWID())
,('Geriatrics',NEWID())
,('Gynecologic Oncology',NEWID())
,('Hematology/Oncology',NEWID())
,('Hepatobiliary',NEWID())
,('Hospitalist',NEWID())
,('Infectious Disease',NEWID())
,('Internal Medicine',NEWID())
,('Interventional Radiology',NEWID())
,('Medical Genetics',NEWID())
,('Neonatology',NEWID())
,('Nephrology',NEWID())
,('Neuroradiology',NEWID())
,('Neurology',NEWID())
,('Neurosurgery',NEWID())
,('Nuclear Medicine',NEWID())
,('Obstetrics & Gynecology',NEWID())
,('Occupational Medicine',NEWID())
,('Ophthalmology',NEWID())
,('Oral Surgery',NEWID())
,('Orthopedics',NEWID())
,('Otolaryngology / Head & Neck Surgery',NEWID())
,('Pain Management',NEWID())
,('Palliative Care',NEWID())
,('Pain Management',NEWID())
,('Palliative Care',NEWID())
,('Pathology: Surgical & Anatomic',NEWID())
,('Pediatric Intensivist',NEWID())
,('Pediatrics',NEWID())
,('Pediatric Surgery',NEWID())
,('Physical Medicine',NEWID())
,('Plastic & Reconstructive Surgery',NEWID())
,('Podiatric Surgery',NEWID())
,('Psychiatry',NEWID())
,('Pulmonary Medicine',NEWID())
,('Radiation Oncology',NEWID())
,('Radiology',NEWID())
,('Rheumatology',NEWID())
,('Surgical Oncology',NEWID())
,('Thoracic Surgery',NEWID())
,('Transplant Surgery',NEWID())
,('Urology',NEWID())
,('Vascular Surgery',NEWID())
,('Wound Care',NEWID())
,('Bariatric Surgery',NEWID())
,('ENT',NEWID())
,('General Surgery',NEWID())
,('Gastroenterology',NEWID())
,('Neurosurgery',NEWID())
,('Obstetrics & Gynecology',NEWID())
,('Ophthalmology',NEWID())
,('Oral/Dental Surgery',NEWID())
,('Orthopedic Surgery',NEWID())
,('Pain Management',NEWID())
,('Pediatric Surgery',NEWID())
,('Plastic Surgery',NEWID())
,('Podiatric Surgery',NEWID())
,('Urology',NEWID())
,('Vascular Surgery',NEWID())
,('Ambulatory Clinics',NEWID())
,('Cardiac Catheterization Labs',NEWID())
,('Diagnostic Radiology',NEWID())
,('Emergency Department',NEWID())
,('GI Endoscopy Labs',NEWID())
,('Inpatient Acute Care',NEWID())
,('Interventional Cardiology',NEWID())
,('Interventional Radiology',NEWID())
,('Same Day Surgery',NEWID())
,('Small Specialty Hospitals',NEWID())
,('Surgical Pathology',NEWID());
